language: node_js
node_js:
- '14'
services:
- redis-server
script:
- echo 'Starting'
- npm install
- echo 'Testing'
- npm test
deploy:
  provider: heroku
  api_key:
    secure: EU5HZU7QQ8V0BNLJUCxshK9nFI0gQMYz4BTtMqbEZzr8WkCpgn7MQEST9p+QCzk59QC4fwjmbhFEpApD4vRRMe6TGp+1PmRo+TxgV3EXZPu9EE6fP5XXQ8kj6Z1tpRSKiE5xiJsQR6jWRt8T8Wu6V8+kW7igz8EeS5PmcLaFWubKKoWbGgInxrWKSpaU3Zdpr9N5cmuhJ8CAhcvc2mvyzYLYqVLnigwZb4LB5WThkGoFx18qOLoPyvH2hP7hX7biEaGOPBX5XRlKVMvfTgxMWhxQ8TLOMxeYcspGig1nfuMKqIVCeZi+dcvpNQMMIJwfmvpn/8JYG0t6Q00QM2TRk4LJuxunK9DJ+nmv2NBbgdSDKoR3MMfLx2zzlV8xQqfGZe2XuaOlQomsKsPYIr6u3XqRlnB0+CKKY7/FK/T4LDykOZN51tjF6U1l/0S+62+33nQRmzbaWVbOhjq0VItJKMOIZpbtpVraZ4OAWwg09GKX5pQsupJh2VG3IRP8pd45GMBbrFTWV0eFaMlVEgnq06WxcS8i8S8GgQlzYtEcmH5j8/F6osDV7YG45oRylaf4++BOEsXTmALjJUXzdfQS3cWMDfTqcaoDz7KlYUUPhxeeaNzG6AU4Z8BGjvJQy93zoY9mY12iMBDVaYTzDhGleMFo+9nC3yCSv2oYvteEPjU=
  app: my-devops-application
  on:
    repo: ThomasRabn/ece-devops-labs
  skip_cleanup: 'true'
