version: '3'
services:
  redis:
    image: "redis:alpine"
    expose:
      - 6379
  
  web:
    image: "thomasrabn/devops-project-app"
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis
    links:
      - redis
    command:
      sh -c "npm test && npm start"