apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-devops-app
  labels:
    app: deployment-devops-app
spec:
  selector:
    matchLabels:
      app: pod-devops-app
  template:
    metadata:
      labels:
        app: pod-devops-app
    spec:
      containers:
      - name: devops-app
        image: thomasrabn/devops-project-app
        ports:
        - containerPort: 3000
      - name: redis
        image: redis:alpine
        # We change the original `redis-server` command to `redis-server --appendonly yes`
        # It launches redis and creates an appendonly file that will allow us to have persistence
        command: ["redis-server"]
        args: ["--appendonly", "yes"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-pv
          mountPath: /data
      volumes:
      - name: redis-pv
        persistentVolumeClaim:
          claimName: redis-pv-claim