---
- name: Install Git and Redis
  yum:
    name:
      - git
      - redis
    state: latest

- name: Download Node.js setup script
  get_url:
    url: https://rpm.nodesource.com/setup_14.x
    dest: /opt
    mode: 755

- name: Setup Node.js to use v14
  command: /opt/setup_14.x

- name: Install Node.js
  yum:
    name: nodejs
